# Generated by Django 4.2.4 on 2023-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=255, verbose_name=' designation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=100, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=255, verbose_name='google_plus_link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100, verbose_name='twitter_link'),
        ),
    ]
