# Generated by Django 4.2.4 on 2023-09-27 16:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_designation_alter_team_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_name',
        ),
        migrations.CreateModel(
            name='TeamTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('first_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('designation', models.CharField(max_length=255, verbose_name=' designation')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.team')),
            ],
            options={
                'verbose_name': 'team Translation',
                'db_table': 'pages_team_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
