# Generated by Django 4.2.4 on 2023-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_team_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100, verbose_name='google_plus_link'),
        ),
    ]
