# Generated by Django 4.2.4 on 2023-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Tanger-Tétouan-Al Hoceïma', 'Tanger-Tétouan-Al Hoceïma'), ("L'Oriental", "L'Oriental"), ('Fès-Meknès', 'Fès-Meknès'), ('Rabat-Salé-Kénitra', 'Rabat-Salé-Kénitra'), ('Béni Mellal-Khénifra', 'Béni Mellal-Khénifra'), ('Casablanca-Settat', 'Casablanca-Settat'), ('Marrakech-Safi', 'Marrakech-Safi'), ('Drâa-Tafilalet', 'Drâa-Tafilalet'), ('Souss-Massa', 'Souss-Massa'), ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'), ('Laâyoune-Sakia El Hamra', 'Laâyoune-Sakia El Hamra'), ('Dakhla-Oued Ed-Dahab', 'Dakhla-Oued Ed-Dahab')], max_length=100),
        ),
    ]
