# Generated by Django 4.2.4 on 2023-09-29 15:10

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_body_style_remove_car_car_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='body_style',
            field=models.CharField(max_length=100, verbose_name='body_style'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='car_photo'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='car_photo_1'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='car_photo_2'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='car_photo_3 '),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='car_photo_4'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_title',
            field=models.CharField(max_length=255, verbose_name='car_title'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='color',
            field=models.CharField(max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='condition',
            field=models.CharField(max_length=100, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, verbose_name='doors'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='engine',
            field=models.CharField(max_length=100, verbose_name='engine'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=255, verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='fuel_type',
            field=models.CharField(max_length=50, verbose_name='fuel_type'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='interior',
            field=models.CharField(max_length=100, verbose_name='interior'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='milage',
            field=models.IntegerField(verbose_name='milage'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='miles',
            field=models.IntegerField(verbose_name='miles'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='model',
            field=models.CharField(max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='no_of_owners',
            field=models.CharField(max_length=100, verbose_name='no_of_owners'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='passengers',
            field=models.IntegerField(verbose_name='passengers'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='state',
            field=models.CharField(choices=[('Tanger-Tétouan-Al Hoceïma', 'Tanger-Tétouan-Al Hoceïma'), ("L'Oriental", "L'Oriental"), ('Fès-Meknès', 'Fès-Meknès'), ('Rabat-Salé-Kénitra', 'Rabat-Salé-Kénitra'), ('Béni Mellal-Khénifra', 'Béni Mellal-Khénifra'), ('Casablanca-Settat', 'Casablanca-Settat'), ('Marrakech-Safi', 'Marrakech-Safi'), ('Drâa-Tafilalet', 'Drâa-Tafilalet'), ('Souss-Massa', 'Souss-Massa'), ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'), ('Laâyoune-Sakia El Hamra', 'Laâyoune-Sakia El Hamra'), ('Dakhla-Oued Ed-Dahab', 'Dakhla-Oued Ed-Dahab')], max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='transmission',
            field=models.CharField(max_length=100, verbose_name='transmission'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='vin_no',
            field=models.CharField(max_length=100, verbose_name='vin_no'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year'),
        ),
    ]
