# Generated by Django 4.2.4 on 2023-09-29 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_created_at_alter_cartranslation_body_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_photo',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_photo_1',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_photo_2',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_photo_3',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_photo_4',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='features',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='no_of_owners',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='vin_no',
        ),
        migrations.RemoveField(
            model_name='cartranslation',
            name='year',
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='body_style',
            field=models.CharField(max_length=100, verbose_name='Body Style'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='car_title',
            field=models.CharField(max_length=255, verbose_name='Car Title'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='fuel_type',
            field=models.CharField(max_length=50, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='cartranslation',
            name='interior',
            field=models.CharField(max_length=100, verbose_name='Interior'),
        ),
    ]
