# Generated by Django 4.2.4 on 2023-09-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_cartranslation_car_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='CarTranslation',
        ),
    ]
