# Generated by Django 4.2.4 on 2023-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_car_photo_car_car_photo_1_car_car_photo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartranslation',
            name='car_title',
        ),
        migrations.AddField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Car Title'),
        ),
    ]
