# Generated by Django 4.2.4 on 2023-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartranslation',
            name='body_style',
        ),
        migrations.AddField(
            model_name='car',
            name='body_style',
            field=models.CharField(max_length=100, null=True, verbose_name='Body Style'),
        ),
    ]
